#!/usr/bin/env bash
# This script reads the /etc/passwd file and displays the username, user id, and home directory.

while IFS=: read -r username _ userid _ _ home _; do
  echo "$username:$userid:$home"
done < /etc/passwd
