#!/usr/bin/env bash
# This script reads the /etc/passwd file and tells a story about each user.

while IFS=: read -r username _ userid group _ home shell; do
  echo "The user $username is part of the $group gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
