#!/usr/bin/env bash
# This script checks if the 'school' file exists, if it is empty, and if it is a regular file.

if [ -e school ]; then  # Check if the file exists
  echo "school file exists"
  
  if [ ! -s school ]; then  # Check if the file is empty
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi
  
  if [ -f school ]; then  # Check if it's a regular file
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
