#!/bin/bash

PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "$PROCESS_NAME is already running."
        else
            /bin/bash ./manage_my_process &
            echo $! > "$PID_FILE"
            echo "$PROCESS_NAME started"
        fi
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill $(cat "$PID_FILE")
            rm -f "$PID_FILE"
            echo "$PROCESS_NAME stopped"
        else
            echo "$PROCESS_NAME is not running."
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "$PROCESS_NAME restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

